version: '3.9'
services:
    web:
        build:
            context: .
            dockerfile: Messenger.Blazor\Dockerfile
        ports:
            - "5002:80"
        depends_on:
            identityserver:
                condition: service_started
            message:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        networks:
            - aspcore-network
    rabbitmq:
        image: rabbitmq:3.9-management
        hostname: rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 10s
            retries: 20
        networks:
            - aspcore-network
    message:
        build:
            context: .
            dockerfile: Message_Service\Dockerfile
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - aspcore-network
        
    identityserver:
        image: identityserver
        build:
            context: .
            dockerfile: IdentityServer\Dockerfile
        ports:
            - "5001:80"
        networks:
            - aspcore-network
    
networks:
    aspcore-network:
        driver: bridge