version: '3.9'
services:
    web:
        image: miksior/messenger-web:latest
        ports:
            - "5002:80"
        depends_on:
            identityserver:
                condition: service_started
            message:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        networks:
            - aspcore-network
    rabbitmq:
        image: rabbitmq:3.9-management
        hostname: rabbitmq
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 20s
            timeout: 20s
            retries: 20
        networks:
            - aspcore-network
    message:
        image: miksior/messenger_api:latest
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - aspcore-network
        
    identityserver:
        image: miksior/messenger_identity:latest
        ports:
            - "5001:80"
        networks:
            - aspcore-network
    
networks:
    aspcore-network:
        driver: bridge